<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>OutlineQuestFlight</AssemblyName>
    <RootNamespace>OutlineQuestFlight</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>References/MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>

<Reference Include="MelonLoader">
  <HintPath>$(MSBuildProjectDirectory)/References/MelonLoader.dll</HintPath>
  <Private>false</Private>
</Reference>

    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>References/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>References/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.XRModule">
      <HintPath>References/UnityEngine.XRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
